language: python
python:
- '2.7'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
# env:
# - GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
install:
- pip install -r requirements.txt
- gcloud config set project kuti-170509
script:
- python test.py
before_install:
- openssl aes-256-cbc -K $encrypted_c622c07d672d_key -iv $encrypted_c622c07d672d_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk;
  export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)";
  echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list;
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -;
  sudo apt-get update && sudo apt-get install google-cloud-sdk;
  fi
- tar -xzf credentials.tar.gz
# - mkdir -p lib
- gcloud --version
- gcloud auth activate-service-account --key-file client-secret.json
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- ssh -i ~/.ssh/google_compute_engine -o "StrictHostKeyChecking no" 104.197.244.245
- cd /home/user/sites/kuti
- git pull
- sudo service nginx restart
# deploy:
# - gcloud compute ssh kuti --zone us-central1-c -q
# after_succes:
# - ssh -i ~/.ssh/google_compute_engine 104.197.244.245
# - cd /home/user/sites/kuti
# - git pull
# - sudo service nginx restart
