language: python
python:
- '2.7'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
install:
- pip install -r requirements.txt
- gcloud config set project kuti
script:
- python test.py
before_install:
- openssl aes-256-cbc -K $encrypted_c622c07d672d_key -iv $encrypted_c622c07d672d_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- export PATH="/usr/lib/google-cloud-sdk/bin:$PATH"    
- tar -xzf credentials.tar.gz
- gcloud auth activate-service-account --key-file client-secret.json
after-success:
- gcloud compute ssh kuti
- cd /home/user/sites/kuti
- git pull
- sudo service nginx restart
